//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SafinShoe
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public string ProductArticle { get; set; }
        public int ProductType { get; set; }
        public string ProductUnit { get; set; }
        public decimal ProductPrice { get; set; }
        public string ProductSupplier { get; set; }
        public string ProductManufacturer { get; set; }
        public string ProductCategory { get; set; }
        public int ProductDiscount { get; set; }
        public int ProductCount { get; set; }
        public string ProductDescription { get; set; }
        public string ProductImage { get; set; }



    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual ProductTypes ProductTypes { get; set; }
    }
}
